### ISSUE TITLE
학습타이머에서 해당 유저가 가지고 있는 전체 타이머 ID(timeLectureIDX) 리스트를 가져오는 API 필요(SB문서 14페이지)

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#1]
>박범일(비상)

정리된 api가 있는것 같아요. 확인한번 부탁드립니다.
https://app.only1.co.kr/conceptSolving/studyTimeList.asp?lp_idx=114494&l_idx=32437&ld_idx=6363870&timeLectureIDX=1

**Comment by KwonGeneral** [comment]
1. 해당 강좌의 lp_idx, l_idx로 timerLectureIDX 전체 조회
2. 위의 조회값에서 강의(ld_idx) ID를 찾아서 timerLectureIDX 찾기
3. 찾은 timerLectureIDX로 학습타이머 시간리스트 가져오기

---
학습타이머 시간리스트
(https://a1.only1.co.kr/conceptSolving/studyTimeList.asp?lp_idx=114494&l_idx=32437&ld_idx=6363870&timeLectureIDX=1)
 -> lp_idx:상품IDX l_idx : 강좌IDX  LD_IDX: 강의 IDX timeLectureIDX : 학습타이머 최초기록IDX

학습타이머 시간리스트를 (조회)가져올 때, timerLectureIDX는 필요 없는 파라미터로 보입니다.
lp_idx, l_idx, ld_idx로만 조회하는게 좋을 것 같습니다.

---

**Comment by jeongyeol-son** [comment]
학습 타이머의 CRUD는  timeLectureIDX가 아니라 LD_IDX로만 이루어져야 할 것 같습니다.

**Comment by parkbeomil** [comment]
timeLectureIDX 파라메타는 입력하지 않아도 리스트 뜨게 해놓았습니다.
말씀하신대로   lp_idx, l_idx, ld_idx 세개를 이용해서 최초의 timeLectureIDX를
찾을수가 있을것 같습니다.
timeLectureIDX파라메타는 안넘겨주셔도 될듯해요.

**Comment by parkbeomil** [comment]
> 학습 타이머의 CRUD는 timeLectureIDX가 아니라 LD_IDX로만 이루어져야 할 것 같습니다.

ld_idx --> lp_idx까지 찾아낼순 있는데 여러개가 있을수 있어서 잘못된 상품,강좌가
출력될수 있을거 같아요. 불가피하게 lp_idx, l_idx도 필요할듯합니당~
(타이머 각 항목 세부 데이터는 timeDetailIdx라고 각 타이머 고유idx있습니다. 요거는  timeDetailIdx만 있으면 되긴하는데 이걸 찾으려면 앞에 값들이 있긴해야해요)

**Comment by parkbeomil** [comment]
* 검토요청 드려요~
4-I : 학습타이머시간 리스트( /conceptSolving/studyTimeList.asp )
-> timeLectureIDX값이 안넘어오면  Lp_idx, l_idx, ld_idx를 이용해 최신거 기준으로 가져오도록 하였습니다.

**Comment by KwonGeneral** [comment]
확인했습니다.
