### ISSUE TITLE
학습이력(개념콕, 문제콕)

### ISSUE THREAD

**Issue by KwonGeneral** [awesomeitdev/onlyonemiddle#10]
- https://app.only1.co.kr/conceptSolving/getStudyHistory2.asp
해당 API에서도 hasMore가 필요합니다.

**Comment by parkbeomil** [comment]
네~ getStudyHistory.asp 요 파일과 동일하게 추가해 놓았습니다.

**Comment by KwonGeneral** [comment]
확인했습니다!
