### ISSUE TITLE
학습타이머 저장 시, 기준점을 모르겠습니다.

### ISSUE THREAD

**Issue by KwonGeneral** [awesomeitdev/onlyonemiddle#12]
H.[학습타이머 저장 [SB - 13]](https://a1.only1.co.kr/conceptSolving/setStudytimeCheck.asp?lp_idx=114494&l_idx=32437&ld_idx=6363870&studySeconds=6578542)
kimnew01로 로그인 lp_idx:상품IDX l_idx : 강좌IDX  LD_IDX: 강의 IDX  studySeconds:체크시간

위의 API 파라미터에서 studySeconds가 second 기준이 아닌 것 같습니다.
밀리세컨드나 세컨드로 변경 부탁드립니다~!

**Comment by jeongyeol-son** [comment]
학습타이머 저장시 저장을 하는 버튼을 누르면 무조건 새기록으로 저장되어야 한다고 확인되었습니다.
그러므로 저장 api에서 각 개별 detail time id를 날리는 방식이 아닌 , 한번에 등록하는 방식 (param의 일부를 spliter를 써서 구분하는 방법이 필요 할 듯 싶습니다.
물론 수정 부분이 있어 기존의 각 detail time을 modify하는 api 또 한 유지 되어야 합니다.

**Comment by parkbeomil** [comment]
12~14페이지가 한 화면 인데
시작 누르면 스톱워치 스타트 하고
13p 구간기록 누를때마다 14p처럼 리스트에 가지고 있다가
14p 저장버튼 누를때 api로 쏴주시면 될듯합니다.

그럼 디비상에는 
이번건의 스탑워치 타임랩 기록묶음에 대한 idx(공부시간노트)를 만들고
각 타임랩들을 구간기록 테이블 (학습타이머idx)에 주루룩 삽입하게 되어있어요

현재는 H.[학습타이머 저장 [SB - 13]](setStudytimeCheck.asp) 요 파일을
구간기록버튼 누를때마다 호출해주는 구조입니다.

다만 구조상,  묶어놨다가 한번에 호출할지 건건이 호출하는게 좋을지 고민해서
쪼개던 하나로 하던 하면 될듯합니다.

**Comment by KwonGeneral** [comment]
네 알겠습니다~

**Comment by jeongyeol-son** [comment]
* 노트 생성,삭제,수정 API 필요
* 타이머 생성(노트id 기준), 수정(timer id),삭제 (timer id)을 기준으로 하는 API들 이 각각 필요합니다.

**Comment by parkbeomil** [comment]
> * 노트 생성,삭제,수정 API 필요
> * 타이머 생성(노트id 기준), 수정(timer id),삭제 (timer id)을 기준으로 하는 API들 이 각각 필요합니다.

* 노트액션(읽기제외)
setStudyNoteAction.asp
* 타이머액션(읽기제외)
setStudyTimerAction.asp

일케 만들도록 하겠습니다. 파라메타랑 정리한번해서 다시 말씀드릴게요.


일단 기존것도 유지되고 있으니 완료되면 그때 적용하시믄 델듯해요.

**Comment by parkbeomil** [comment]
변경되는 부분은
노트 처리 후 타이머 액션처리를 순차적으로 실행해야 합니다.
(기존엔 타이머 기록하면 노트 자동생성후 타이머 등록처리같은것도 되었는데
각 액션을 분리해서
타이머 처리는 타이머에서 하고
노트처리는 노트에서 하게 쪼겠어요)


 * 프로세스
1. 노트가져오기(없으면 생성)

2. 타이머 버퍼에 리스트 생성 후

3. 저장시 건바이건으로 기존 파라메타 + 노트idx로 저장 타이이머 호출

4. 저장후에는 다시 새 노트idx 가져오기(1번부터 반복)


욜케 정리하겠습니당.

**Comment by KwonGeneral** [comment]
타이머를 저장할 때, 노트에 매칭이 안되는 것 같습니다.

1. https://app.only1.co.kr/conceptSolving/setStudyTimerAction.asp?actionType=C&lp_idx=115555&l_idx=32606&ld_idx=6429330&timeLectureIDX=167&studySeconds=0
2. https://app.only1.co.kr/conceptSolving/setStudyTimerAction.asp?actionType=C&lp_idx=115555&l_idx=32606&ld_idx=6429330&timeLectureIDX=168&studySeconds=0

위의 API를 연달아서 날렸을 때, timeLectureIDX_167과 168의 노트 각각에 해당하는 타이머가 저장되어야하는데, 현재는 timeLectureIDX_167에 2개의 타이머 모두 저장이 되고 timeLectureIDX_168은 타이머 기록이 없음으로 저장이 되고있습니다.

1. https://app.only1.co.kr/conceptSolving/getStudyNoteTimeLine.asp?lp_idx=115555&l_idx=32606&LD_IDX=6429330&timeLectureIDX=167
2. https://app.only1.co.kr/conceptSolving/getStudyNoteTimeLine.asp?lp_idx=115555&l_idx=32606&LD_IDX=6429330&timeLectureIDX=168

위의 2개의 API를 확인해보면, 1번 API에만 타이머 기록이 존재합니다.
확인 부탁드립니다~~

추가로, 타이머 삭제가 제대로 동작을 안하는 것 같습니다.

**Comment by parkbeomil** [comment]
넹 체크해서 조정하엿습니다~

**Comment by parkbeomil** [comment]
강의재생전에 게이트 페이지에서 타이머 기록을을 위한 버튼영역이 표시가 안되고 있습니다.
위에 처리 관련해서 테스트 할때는 제가 플래그로 켜고 끄면 보였다 사라졌다 했는데 
지금은 플래그를 바꿔보고 강제로 타이머있는것으로 하드코딩해도 표시가 안되는데 
따로 체크하는 값이 있을가요? 
getConceptProcess.asp랑 getLectureDTimeAndCountingInfo.asp랑 두군데서 이것저것
바꺼밨는데 안되고 있어서 체크할거 있는지 문읟립니당.

**Comment by parkbeomil** [comment]
> 

타이머표시관련해서 완료되었습니다.

**Comment by KwonGeneral** [comment]
여전히 타이머 삭제가 제대로 동작을 안하는 것 같습니다

**Comment by parkbeomil** [comment]
타이머 삭제는 없애는걸로 정리하였습니다.
