### ISSUE TITLE
공부시간노트, 강의별 상세 학습기록 보기 API에서 timeDetailIdx 필드 Blank

### ISSUE THREAD

**Issue by KwonGeneral** [awesomeitdev/onlyonemiddle#13]
O. [강의별 상세 학습기록 보기[SB - 20 , 21, 22]](https://app.only1.co.kr/conceptSolving/studyNoteTimeLine.asp?lp_idx=114494&l_idx=32437&LD_IDX=6363870&timeLectureIDX=1)
---
현재 해당 API(https://a1.only1.co.kr/conceptSolving/studyNoteTimeLine.asp)에서 구간기록 IDX(timeDetailIdx)를 주고 있지 않습니다.

**Comment by parkbeomil** [comment]
timeDetailidx 에 값 출력하게 하였습니다~

**Comment by KwonGeneral** [comment]
확인했습니다~!
