### ISSUE TITLE
플레이어, 학습 종료 시, 다음 강의 바로 듣기의 링크가 유효한지 확인이 필요합니다.

### ISSUE THREAD

**Issue by KwonGeneral** [awesomeitdev/onlyonemiddle#14]
https://app.only1.co.kr/soobakcPlayer/getLectureEndInfo.asp?Lp_IDX=114494&LD_IDX=6363880&lh_idx=0&studyTime=1&QockIDX=3050717&L_IDX=32437
---
학습 종료 시, 위의 API를 호출하는데, 기존에는 nextLessonMovie 링크를 통해 다음 영상을 재생했습니다.
그런데 현재 개념문풀 작업을 하면서 콕 강의 리스트에서 다음 Index의 영상이 나와야할 것 같은데, 전혀 다른 영상이 재생되어서
이게 맞는건지 아닌건지에 대해서 확인이 필요합니다.

**Comment by parkbeomil** [comment]
현재 일반강의 기준 다음강의가 나오게 되어 있는데
콕강의의 다음강의에 대한 처리 체크하고 말씀드리겠습니다~

**Comment by parkbeomil** [comment]
요거 내용 확인했는데 콕강의(개념콕 문제콕등)는 강의종료하고 다음강좌로 이동이 아니고, 기존 북마크 기능처럼 플레이 화면내에서 이동하는 것이라고 합니다.
북마크바 자리에 https://app.only1.co.kr/conceptSolving/getQockLectureList.asp 요거를 뿌려서 클릭또는 종료시 이동하면 될듯합니다.

**Comment by KwonGeneral** [comment]
확인했습니다~!
