### ISSUE TITLE
[테스트후 문의] 개념학습 진행률 - SB [7-2, 11-3, 11-6]

### ISSUE THREAD

**Issue by parkbeomil** [awesomeitdev/onlyonemiddle#15]
getConceptProcess.asp 에서
ld_idx(강의코드)가 있어야 합니다.[p11-3]
개념콕, 문제콕등의 카운트는 강의코드가 있어야해요.

그리고 교재정보는 [p11-6]
/lecture/getLectureInfoBook.asp?lp_idx=119398
요기서 불러오면 될거 같습니다.

**Comment by KwonGeneral** [comment]
getConceptProcess.asp에서 ld_idx의 필요성은 이해했습니다~!

다만, /lecture/getLectureInfoBook.asp?lp_idx=119398 해당 API에서는 교재명은 파악이 가능하지만, page의 start, end값과 학습기록에 대한 부분을 파악할 수가 없네요.

현재 해당 교재정보에 대한 값들은 [https://app.only1.co.kr/conceptSolving/studyTimerInfo.asp?lp_idx=114494&l_idx=32437&ld_idx=6363870] 이 API를 통해서 값을 가져오고 있었는데,

[/lecture/getLectureInfoBook.asp?lp_idx=119398] 해당 API를 통해서 교재정보를 가져와야하는 이유가 있을까요?

**Comment by KwonGeneral** [comment]
현재 getConceptProcess.asp에서 ld_idx가 필수값이 되어있습니다!
이렇게되면 [SB-7]에 해당하는 강좌의 전체 개념+문제 진도율을 표시할 수 없습니다~!
ld_idx가 없는 경우에는 l_idx(강좌IDX)에 해당하는 전체 개념+문제 진도율을 표시해주시거나 API를 만들어 주실 수 있으실까요~?

**Comment by parkbeomil** [comment]
https://app.only1.co.kr/conceptSolving/getStudyTimerInfo.asp에서 가져오도록 하겠습니다~
이곳에서 교재정보 있는지 몰랐어요. 여기 있는 bookInfo 필드 하위값들 참조하시면 되겠습니다.

**Comment by parkbeomil** [comment]
> 현재 getConceptProcess.asp에서 ld_idx가 필수값이 되어있습니다! 이렇게되면 [SB-7]에 해당하는 강좌의 전체 개념+문제 진도율을 표시할 수 없습니다~! ld_idx가 없는 경우에는 l_idx(강좌IDX)에 해당하는 전체 개념+문제 진도율을 표시해주시거나 API를 만들어 주실 수 있으실까요~?

----------------
체크해보도록 할게요~ 잠시만요.

=> 교거 진도율을 강의(ld_idx)의 시간중에서 실제로 들은 시간이 얼마인지를 계산 하는 방식이라
강의코드(ld_idx)가 꼭 필요합니다. (플레이어를 홀출하면 어짜피 ld_idx는 필수이니 문게없지 않을가
싶은데 ld_idx가 없는 케이스가 잇을가요?)

**Comment by KwonGeneral** [comment]
[SB 7-1]에 보시면, 현재 개념.문제의 "개념학습 진행률", "문제풀이 진행률"에 대한 값을 얻어와야하는데 해당 부분은 강의(ld_idx)가 아니라 강좌라서 조회가 불가능한 것도 있지만, 해당 부분은 통합적인 통계를 표시해줘야해서 각 개별의 강의(ld_idx)에 대한 진도율이 아니라 종합적인 진도율을 표시해줘야합니다~!

**Comment by parkbeomil** [comment]
> 

네 그러면 getConceptProcess.asp얘는 7-1에서만 쓰는거죠?
getLectureDTimeAndCountingInfo.asp얘가 7-2,3번 하고 9-3, 11-3 이겠네요.
조정해 놓겠습니다.

**Comment by parkbeomil** [comment]
매니저님 요거 몇가지 이슈가 있네요. 
SB 7-1하고, 게이트페이지[SB 9~11]에서도
getConceptProcess.asp 요기를 바라보고
있는것 같습니다.

getConceptProcess.asp 요거는 플레이어뜨기전 게이트 페이지[SB 9~11]에서사용하고
getLectureConceptProcess.asp를 강의리스트 페이지( sb[7-1])에서 호출 하실 수 
있도록 작업해 놓겠습니다.


==> getLectureConceptProcess.asp?lp_idx=1111&l_idx=2222 두개 넘겨주시면
개념학습, 문제풀이의 갯수 및 진행율 가져오게 처리하였습니다.
(강의 탭의 나의 진도율, 권장진도율은 기존 api( getMyLectureInfo.asp ) 그대로 이용해 
주시면 되겠습니다~)

**Comment by KwonGeneral** [comment]
네, [SB 7-1] 부분은 getLectureConceptProcess.asp 해당 API를 통해서 처리해놓겠습니다~

**Comment by parkbeomil** [comment]
넹 감사합니다. 요걸 몰라서 계속 삽질하고 있었어요. 
두개를 따로 바야 하는데 하나로 착각하고있엇습니다. ㅋㅋㅋ

**Comment by KwonGeneral** [comment]
넵ㅎㅎ 처리완료했습니다~!
