### ISSUE TITLE
[공부시간노트>상세보기] 리스트 정렬 요청

### ISSUE THREAD

**Issue by KwonGeneral** [awesomeitdev/onlyonemiddle#17]
https://app.only1.co.kr/conceptSolving/studyNoteDetail.asp

안성희CP님이 작성일 기준으로 정렬되어있는 부분을 최근 생성된 노트가 TOP으로 올라가도록 해달라고 합니다~! 
해당 API 내용물 정렬해서 주실 수 있을까요?

**Comment by parkbeomil** [comment]
네~ 알겠습니당.
(어제는 저희 메타인지쪽 연동들이 있어 처리가 좀 늦었어요. 죄송합니다~)

**Comment by parkbeomil** [comment]
타임랩 idx 역순으로 처리 하였습니다.

근데 문의주신것은 타입랩 기록할때 보여지는 순서(디비기록전)를 역순으로 보여달라고 하는거 같아요.
확인한번 부탁드립니다.
