### ISSUE TITLE
메타학습 장애를 대비한 데이터 추가

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#18]
/system/getConfig.asp 에
<metaStudyStatus>0</metaStudyStatus>                         
<metaStudyStatusMessage><![CDATA[점검중,장애처리중 등등등]]></metaStudyStatusMessage> 
이렇게 두개 추가했어요.

0일때 metaStudyStatusMessage 요기 텍스트를 다이얼로그로 출력

출력 타이밍은 메타학습을 실행 시킬 때 매번 이 플래그를 보고 출력한다.

**Comment by KwonGeneral** [comment]
확인했습니다.
