### ISSUE TITLE
메타 인지 학습 링크

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#19]
메타인지학습앱 기능중에 오픈시 안정성이 불안한 메뉴 몇개를 가리고 
다른 메뉴로 바꾸는식으로 살짝 조정 되었어요.
관련해서 메타인지학습앱 호출하는 부분들 action 값을 조정해야 할 듯
합니다.

* 전체메뉴에서 나오는 링크
    - 오늘의미션 : todayMission
    - 자율미션 : subjectMission
    - 메타박스 : myNote
    - 학습현황 : studyStatus
    - 완공서랍 : onlyDic

* 메인화면 오른쪽 영역에 나오는 링크
    - 미션다이어리 : missionDiary
    - 나의 오답 : reviewNote
    - 나의 노트 : myNote

요걸로 action값을 변경해 주시면 되겠습니다.

**Comment by jeongyeol-son** [comment]
@parkbeomil  todayMission 이 보내주신 메일은 todaymission 인데 기존으로 봐서는 대문자가 맞겠죠?

**Comment by KwonGeneral** [comment]
수정했습니다.

**Comment by Awesomeit-NSM** [comment]
추가 요청입니다.
@KwonGeneral 

아래를 참고해 수정 부탁드립니다.
- 오늘의미션 : todayMission
- 자율미션 : freeMission  
- 메타박스 : myNote
- 학습현황 : myMetaLevel
- 완공서랍 : onlyDic
