### ISSUE TITLE
학습타이머 구간기록 TimeRowName명을 수정할 수 있는 API 필요 (SB문서 14페이지)

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#2]
>박범일(비상) 
 빠르게 체크해보고 회신 드릴게요.

**Comment by parkbeomil** [comment]
체크중에 있습니다~

**Comment by parkbeomil** [comment]
apilist.asp에서
4.A 학습타이머 제목수정[SB-14] 로 api생성해 놓았습니다.
timeDetailIDX : 변경할 타이머 idx (studyTimeList.asp의 timeDetailIDX)
title : 변경될제목

욜케 두개 주시면 될듯하고 점심전에 완료해 놓을게요~

**Comment by parkbeomil** [comment]
완료 및 테스트 하였습니다.
(setStudyTimerTitle.asp)

**Comment by KwonGeneral** [comment]
확인했습니다~
