### ISSUE TITLE
 https://app.only1.co.kr/soobakcPlayer/getLectureEndInfo.asp 에서  개념콕,문제콕 일 경우 원 영상 URL 주소와 원영상의 전체 길이를 반환

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#21]
https://app.only1.co.kr/soobakcPlayer/getLectureEndInfo.asp 에서  개념콕,문제콕 일 경우 원 영상 URL 주소와 원영상의 전체 길이를 반환하는 값이 필요합니다.

![버그13번](https://user-images.githubusercontent.com/66989039/208341279-ee272a62-a15f-45bd-821f-c13d5c7f726e.PNG)

**Comment by parkbeomil** [comment]
https://app.only1.co.kr/soobakcPlayer/getLectureEndInfo.asp  파일끝에

originalMovieURL과
originalMovileTime필드 추가했습니다.

한가지 말씀드릴게 있는데 originalMovieURL 요부분은 토큰을 적용시켜서 재행해야되가지고
부득이 mp4직 링크를 적용할 수가 없어서 getStreamingMovieInfo.asp파일 호출할수 있게
url과 파라메타 정보를 출력햇어요. 확인한번 부탁드립니다~

**Comment by KwonGeneral** [comment]
네~ 해당 부분은 추가해주신 값을 통해 처리해놓겠습니다!
