### ISSUE TITLE
콕강의 진행도 관련 이슈

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#22]
콕강의를 실행후 마지막까지 재생되게 대기 하면
자동종료되는 팝업에서 2개를 모두 들었는데 0개 들었다고 결과값이 나오고
게이트로 나가기 했을때도 진도율이 반영되지 않습니다.
콕강의를 터치하고 나가기 하면 카운팅 반영이 되어 추가 확인 필요합니다.

이게 케이스가 명확하지 않아서... 좀더 확인해보겠습니다.

*확인 결과 setStudyTime에 콕강의 진도율을 연동 해 놓으신듯 합니다.
그래서 강의 시작 일 때 setStudyTime을 먼저 한번 걸었는데 일단 영상내 학습 카운트는 정상적으로 올라가나  (1개의 콕강의를 이수했음)
게이트 페이지의 진도율이 이상하게 표시 되네요.
api는 아래와 같습니다.
-영상 내 API
https://app.only1.co.kr/soobakcPlayer/getLectureEndInfo.asp?Lp_IDX=129687&LD_IDX=6717930&lh_idx=0&studyTime=0&QockIDX=3839077&L_IDX=33351

-게이트 내 API
https://app.only1.co.kr/conceptSolving/getConceptProcess.asp?l_idx=33351&ld_idx=6717930

**Comment by parkbeomil** [comment]
요건 아마 LP_IDX가 없어서 그런것 같아요.
getConceptProcess.asp 요기에 LP_IDX가 안넘어오면
L_IDX가지고 LP_IDX뽑아내게 추가해 놓앗는데
두개가 N:N관계이다 보니 다른게 나올수 있는거 같아요.
getConceptProcess.asp 에 LP_IDX를 넘겨주실수 있을가요?

**Comment by jeongyeol-son** [comment]
https://app.only1.co.kr/conceptSolving/getConceptProcess.asp?lp_idx=119392&l_idx=32437&ld_idx=6558920
lp idx를 추가하였지만 진행율이 다르긴 하네요.

**Comment by parkbeomil** [comment]
getConceptProcess.asp에서 콕강의 여려개 들었을때 동일 콕강의코드에대해서 중복제거를 안해서 더 많게 나왔었네요
처리하였습니다.
