### ISSUE TITLE
공부시간노트 리스트 정보[SB - 18 ], hasMore 값을 주실 수 있을까요? 

### ISSUE THREAD

**Issue by KwonGeneral** [awesomeitdev/onlyonemiddle#24]
https://app.only1.co.kr/conceptSolving/getStudyNoteList.asp

해당 API에서 gotoPage를 하기 위해, hasMore값을 주실 수 있을까요?

**Comment by parkbeomil** [comment]
넹 바로 추가하고 말씀드릴게요~

**Comment by KwonGeneral** [comment]
넵 감사합니다~

**Comment by parkbeomil** [comment]
추가 하였어요~


<pagingInfo>	
<gotoPage>1</gotoPage>
<pageCount>1</pageCount>
<hasMore>0</hasMore>
</pagingInfo>

**Comment by parkbeomil** [comment]
```
<pagingInfo>	
   <gotoPage>1</gotoPage>
   <pageCount>1</pageCount>
   <hasMore>0</hasMore>
</pagingInfo>
```

**Comment by KwonGeneral** [comment]
확인했습니다. 감사합니다~

**Comment by parkbeomil** [comment]
네~
