### ISSUE TITLE
플레이어에서 진도저장 팝업 내  [다음 강의 바로듣기] 버튼 클릭시,  1강에서 2강의로 이동해야 하는데, 1강의의 콕강의 부분이 이동하는것으로 보입니다. 이 부분 확인 부탁드려요~

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#25]
문제콕 혹은 개념콕에서 호출 할 때
https://app.only1.co.kr/soobakcPlayer/getLectureEndInfo.asp?Lp_IDX=124268&LD_IDX=6614720&lh_idx=0&studyTime=0&QockIDX=3819389&L_IDX=33091

응답 다음 강의 url
https://app.only1.co.kr/mypage/getStreamingMovieInfo.asp?lp_idx=124268&lh_idx=0&ld_idx=6614730

개념+문제에서 호출 할 때
>>https://app.only1.co.kr/soobakcPlayer/getLectureEndInfo.asp?Lp_IDX=124268&LD_IDX=6614720&lh_idx=10895833&studyTime=0&QockIDX=&L_IDX=33091
응답 다음 강의 url
 https://app.only1.co.kr/mypage/getStreamingMovieInfo.asp?lp_idx=124268&lh_idx=10895833&ld_idx=6614730

**Comment by jeongyeol-son** [comment]
기획 상 개념혹은 문제콕에서도 다음 강의가 활성화 되어야 하는것으로 보입니다.

**Comment by parkbeomil** [comment]
l_idx로 역산해서 lp_idx불러올때처럼 
lh_idx도 역산해서 불러오면 다른거를 불러 올수도 있을것 같아요.

콕콕개념+문제(lh_idx가 있는애) 이면 다음강의바로듣기가 있고
개념콕, 문제콕들은 다음강의 바로듣기를 숨기는게 어떨가 합니다.
(나머지 버튼들 위치만 가운데로 살짝 몰아주면 어떨가 싶어요)

**Comment by parkbeomil** [comment]
26번이슈로 정리된것 같습니다.
