### ISSUE TITLE
플레이어 관련 문의사항

### ISSUE THREAD

**Issue by parkbeomil** [awesomeitdev/onlyonemiddle#26]
매니저님 안녕하세요~

수정사항으로 두개 접수 된것이 있어 문의드려요.

- 개념, 문제콕 강의 이어보기 관련 
  개념콕, 문제콕에서도 이어보기 옵션이 유지되게 수정 부탁드립니다
  인덱스 3개까지 듣고 나갔다가 다시 재생하는 경우 3번째 부터 재생되도록 부탁드립니다.
   -> 이런식으로 구현할 경우에 api에 추가로  전달드릴게 있을가요?  현재 개념강의수, 문풀강의수는
  api에 있는데 어디까지 들었는지는 없는 상태이긴 합니다. 재생했던 카운트가 몇갠지 드리면
 될거 같긴한데 이부분은 조금더 분석해 봐야 할듯해서 혹시 괜찮은 팁이 있으면 말씀 부탁드려요.

 
- 재생후 진도 결과 팝업(검정색)
  이 팝업에서는 해당 플레이어 에서 수강한 내용만 카운팅되게 수정 부탁드립니다.
  첫번째 재생시, 콕강의를 3개 듣고 두번째 재생시 2개 들었을때 결과창에 총 3개가 아니라 
  현재 떠있는 플레이어에서 2개가 재생된걸로 보였으면 합니다.
  -> 이거 카운트는 디비기준으로  카운트 하는거라 현재플레이어에서 몇갠지 체크는 애매한데,
       플레이어가 재생된 카운트를 가지고 있다가 보여줄 수 있을가요?

**Comment by parkbeomil** [comment]
1.개념, 문제콕 강의 이어보기 관련
2.재생후 진도 결과 팝업(검정색)

1번은 오늘작업하기엔 공수도 크고 오류에 대한리스크도 있으니 추후에 정리하는걸로 얘기하였습니다. 얘는 패스
2번은 수강종류하고 수강요약화면 팝업 (/soobakcPlayer/getLectureEndInfo.asp에서 가져오는 내용들) 에서
일반강좌(콕콕개념+문제)는 기존처럼 나오고 개념콕,문제콕들은 "총00개의 " 를 빼고 그냥 
개념 콕을 학습하셨습니다. 랑,
문제 콕을 학습하셨습니다. 로
출력하게 부탁드립니다.

**Comment by jeongyeol-son** [comment]
처리되었습니다.
