### ISSUE TITLE
공부시간노트 에서도 상세페이지 내용을  삭제 하면  , 삭제를 하려고 했던 부분은  삭제가  안됩니다.

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#27]
-삭제 전 API
https://app.only1.co.kr/conceptSolving/getStudyNoteTimeLine.asp?lp_idx=127769&l_idx=33624&LD_IDX=7041430&timeLectureIDX=485

-삭제
https://app.only1.co.kr/conceptSolving/setStudyTimerAction.asp?actionType=D&lp_idx=127769&l_idx=33624&ld_idx=7041430&timeDetailIDX=2382
>처리 완료 

(<timeDetailidx>2382</timeDetailidx>

<LP_IDX>127769</LP_IDX>
<L_IDX>33624</L_IDX>
<LD_IDX>7041430</LD_IDX>)

-삭제 후 재호출
https://app.only1.co.kr/conceptSolving/getStudyNoteTimeLine.asp?lp_idx=127769&l_idx=33624&LD_IDX=7041430&timeLectureIDX=485

* 삭제 전  데이터와 삭제 후 데이터 가 동일한 것으로 보아 삭제가 제대로 안 이루어지는 듯 합니다.

**Comment by parkbeomil** [comment]
삭제기능 사용안하는것으로 정리하였습니다.
