### ISSUE TITLE
<강의리스트> <나의공부방> 진도율 상이하여 확인 요청 드립니다.

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#28]
제목 : 사과잼  아래 API에서는 40%
https://app.only1.co.kr/myPage/getMyLectureList.asp?subjectCode=AT003&teacherID=&isChapterTest=0

세부 화면에서는 20%
https://app.only1.co.kr/myPage/getMyLectureInfo.asp?lp_idx=124857&lh_idx=10806469

**Comment by Awesomeit-NSM** [comment]
테스트 계정은 harueuki / !s252125 입니다.

**Comment by parkbeomil** [comment]
해당 내용 처리 하였습니다.
기존에 진도오류 있던건데 계속 표시되는 듯합니다.
다시한번 수강시 진도 반영및 수강 완료표시되는것 확인했습니다.

**Comment by parkbeomil** [comment]
네 조정하였습니다~
(이슈들 리스트업된거 외에 혹시나 다른데도 진도율나오는데는 찾아서 바꿔놓도록 할게요)
