### ISSUE TITLE
수강이력보기 팝업 문의

### ISSUE THREAD

**Issue by parkbeomil** [awesomeitdev/onlyonemiddle#29]
수강이력보기 팝업중에
개념콕 이나 문제콕ㅇ서
본강좌는 [개념콕 강의 or 문제콕강의]플 지원하지 않습니다
메세지 표시 기준좀 알켜주세요

수강기록이 없어서 데이터가 없을때도 있고
지원하지 않는 강좌라서 없을수도 있는데 
지금은 잘나오는거 같다가도 어쩔땐 다르게 나오는거 같아서
확인차 문의드립니다.

**Comment by jeongyeol-son** [comment]
- getConceptProcess.asp 또는 getLectureDTimeAndCountingInfo.asp에서 isTimerService=0일경우 적용해주시면 되겠습니다./ 박범일

- 221219 권태완, getLectureDTimeAndCountingInfo.asp의 isTimerService 필드 값을 통해 처리했습니다.
- 221219 노승명 v5.3.0.00)확인완료
- 221220 권태완 처리완료
- 221220 노승명 v5.3.3.00) 확인 완료

QC 시트 16번에 이렇게 써져 주셨는데 지금 봐서는 구조자체가 이상하긴 하네요. 개념콕과,문제콕을 따로 지원 여부를 봐야할거 같은데 말씀 주신걸로는 둘다 같이 처리 하라는 말씀이신것 같아요.

**Comment by jeongyeol-son** [comment]
https://app.only1.co.kr/conceptSolving/getLectureDTimeAndCountingInfo.asp?lp_idx=105561&l_idx=30762&ld_idx=5648330

**Comment by parkbeomil** [comment]
네 그르면 학습이력팝업에 메세지는
getLectureDTimeAndCountingInfo.asp요 페이지의 값중에서
isSolvingMsg 에다가 문제콕을 지원하는지, 개념콕을 지원하는지
출력하도록 하겠습니다.

다만 수강 이력에대해서는 요 api에서 확인이 어려우니 수강내역이 없을경우에만
isSolvingMsg내용을 뿌려주시면 해결될듯한데

가능할가요~~? (구조가 좀 이상하긴 합니다.ㅠ.ㅠ)

**Comment by jeongyeol-son** [comment]
음 뭔가 이상하긴 한데요? 제일 스탠다드 한건 , 값에다가 isSolving (0:미지원 ,1:지원) isCock(0:미지원,1:지원) 이 값만 넘겨 주시면 될듯 한데요?

**Comment by parkbeomil** [comment]
네 iscock에 해당하는값이 있는걸로 잘못알았습니다~

getLectureDTimeAndCountingInfo.asp 여기서

lectureDInfo필드하위에
isQockType1 개념콕지원여부 (0:미지원, 1:지원)
isQockType2 문제콕지원여부 (0:미지원, 1:지원)
이렇게 출력하도록 해놓았습니다.

**Comment by jeongyeol-son** [comment]
개발 확인되었습니다. @Awesomeit-NSM

**Comment by Awesomeit-NSM** [comment]
앱단 확인 완료되었습니다.
