### ISSUE TITLE
현재 학습이력 API에서는 문풀지원여부를 강의ID(ld_idx)로만 알 수 있음.  ld_idx를 모르면 문풀지원여부를 알 수 없음.

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#3]
수강중인강좌 상세>강의목록 페이지에서 해당 강좌(l_idx)가 개념콕, 문제콕 강의를 지원하는지 여부를 표시해줘야 해서 필요함.

>박범일(비상)
요기에 강의시간, 개념콕,문제콕을 표시하는 api인데 다른것일가요?
https://app.only1.co.kr/conceptSolving/lectureDTimeAndCountingInfo.asp?lp_idx=114494&l_idx=32437&ld_idx=6363870

**Comment by KwonGeneral** [comment]
lp_idx: 상품 코드, l_idx: 강좌 코드, ld_idx: 강의 코드 // 해당 강좌(l_idx)가 개념콕, 문제콕을 지원하는지 여부를 확인할 수 있어야하는데,
강의(ld_idx)까지 알아야지 개념콕, 문제콕 여부를 확인할 수 있어서, 현재는 해당 강좌의 강의 목록을 전체 불러온다음에 해당 강의들로 다시 조회를해서
개념콕, 문제콕 지원 여부를 확인해야합니다.
강좌(l_idx)로만 개념콕, 문제콕 지원여부를 확인할 수 있었으면 합니다.

**Comment by parkbeomil** [comment]
아 그러면 해당 강좌(l_idx또는 lp_idx)만 가지고도 하위 강의에 개념콕,문제콕이 있는강의가 있는지 체크해서
플래그 찍으면 될가요?
(수강중인 강좌 상세의 강의목록에 있는 아래 코드처럼)
`<isGateView>0</isGateView>	<!-- 개념문풀 존재여부 (0: 비노출, 1: 노출)-->`

**Comment by KwonGeneral** [comment]
- https://a1.only1.co.kr/conceptSolving/conceptProcess.asp
위의 API에다가 (https://a1.only1.co.kr/conceptSolving/lectureDTimeAndCountingInfo.asp) 해당 API의 [ isSolving ] 처럼 플래그 찍혀있었으면 합니다.

**Comment by parkbeomil** [comment]
그러면 conceptProcess.asp에 다가 isSolving 필드 하나 추가 하면 될가요?
```
<QockProgressInfo>
	<isSolving><![CDATA[<%=isSolving%>]]></isSolving><!--개념문풀강의 지원여부 1:지원 0: 미지원-->
        .....
```

**Comment by parkbeomil** [comment]
```
<QockProgressInfo>
      <isSolving><![CDATA[<%=isSolving%>]]></isSolving><!--개념문풀강의 지원여부 1:지원 0: 미지원-->
      .....
```
일단 위처럼 추가하였습니다~

그리고 파일명좀 변경했으면해요.(오류는 아닌데 파일명규칙에 안맞아서...)
getConceptProcess.asp 요걸로 동일한파일 하나 더 만드어 놓았어요.
변경해주시면 기존파일은 지우도록 하겠습니다.

아 하나 더 있었네요.
lectureDTimeAndCountingInfo.asp요것도 getLectureDTimeAndCountingInfo.asp 이걸로
변경부탁드립니다.

**Comment by KwonGeneral** [comment]
확인했습니다!
