### ISSUE TITLE
학습타이머 학습시간 관련 문의

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#30]
로그인 정보

https://app.only1.co.kr/login/login.asp?userID=harueuki&userPWD=!s252125&deviceID=123&token=asdkk123kskf&osType=android&deviceType=phone&deviceModel=LG_FS320S&osVersion=android%204.4.2

공부시간 노트 상세
https://app.only1.co.kr/conceptSolving/getStudyNoteDetail.asp?lp_idx=129555&l_idx=33186

강의 게이트웨이 페이지
https://app.only1.co.kr/conceptSolving/getStudyTimerInfo.asp?lp_idx=105561&l_idx=30762&ld_idx=5648330

에서 토탈 타임을 넘겨주는 것으로 확인했지만 여전히 학습 기록이 0분 0초로 나오고 있습니다.
확인 좀 부탁 드릴께요.

**Comment by parkbeomil** [comment]
실제 타이머 기록이 없으면
토탈타임으로 넘어오는 값으로 치환했는
타이머기록 있는지 없느지 체크할때 널체크를 빼서 안나왔네요~
처리하였습니다.

**Comment by jeongyeol-son** [comment]
총학습시간이 있는 api 가 아래와 같이 또 있어서 이 부분에서도 확인 부탁 드리겠습니다.

https://app.only1.co.kr/conceptSolving/getStudyNoteDetail.asp?lp_idx=105561&l_idx=30762

**Comment by parkbeomil** [comment]
네 해당부분 도 변경하였어요.

**Comment by Awesomeit-NSM** [comment]
@parkbeomil 
CP님 '인트로(게이트) 페이지>학습기록'이 현재 '최근 기록의 구간 기록 中 가장 큰 값' 을 넘겨주시는 것 같습니다.
총 학습 시간으로 수정이 필요할 것 같습니다.
![Screenshot_20221221-160746](https://user-images.githubusercontent.com/70569321/208842909-42d19753-f1ee-4107-b71d-65b61d3a2da2.jpg)

**Comment by parkbeomil** [comment]
시간비교 없애고
totalTime으로 받은값으로 표시되게 
해 놓았습니다~

**Comment by Awesomeit-NSM** [comment]
앱단 확인 완료되었습니다.
