### ISSUE TITLE
강의 목록에 학습진도 영역 소수점 첫째자리까지 노출될 수 있게 수정 부탁드립니다.

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#31]
#28  관련 사항

- 221220 노승명)현재 정수 형태로 값을 주시는데 아래 API를 참고해 소수점 첫째자리까지 값을 넘겨주세요.

**Comment by jeongyeol-son** [comment]
<SolvingMyCount>
<![CDATA[ 105561 ]]>
</SolvingMyCount>

*https://app.only1.co.kr/conceptSolving/getLectureConceptProcess.asp?lp_idx=105561&l_idx=30762

위 API 중 카운트가 10만이 들어오는 현상이 있습니다.


<studyPercent>
<![CDATA[ 20 ]]>
</studyPercent>

<recommendStudyPercent>
<![CDATA[ 6 ]]>
</recommendStudyPercent>

*https://app.only1.co.kr/myPage/getMyLectureInfo.asp?lp_idx=105561&lh_idx=10942055

여전히 진도율이 소수점으로 반환되지 않습니다.
@parkbeomil

**Comment by parkbeomil** [comment]
처리하였습니다.
(아까 제가 api값 확인차 몇개 찍어보다가 10만 계속직히는경우가 있었어요. 혼선을 드려 죄송합니다~)

**Comment by parkbeomil** [comment]
getLectureConceptProcess.asp 여기 진행률 표시관련 문의인데요~

ConceptProgressBar 및 SolvingProgressBar의 값이 없을경우에(수강을 아직 한번도 안했을때)는
강의갯수정보들이 표시 되지 않는것 같습니다.
강제로 ConceptProgressBar 및 SolvingProgressBar에 수동으로 값을 넣어보면 잘 출려되요.
(소숫점이면 안나오는거 같기도 합니다. 값이없거나 소수일경우 표시안되는거 같아요)

확인한번 부탁드립니다.

**Comment by jeongyeol-son** [comment]
위 사항 확인하였습니다. 일단 예전 기존 어플의 진도율은 자연수 값이 아니면 대응이 안되게 되어있습니다. 소수점 자리 값이 오면 패널을 하이드 시키게 되어있네요.
일단 지금 배포버전에서는 대응이 되게 하였습니다만 문제는 기존 사용자들이 문제가 생길 수 있는지라 강의 진도율의 경우는 신중히 검토가 필요 할 듯 싶습니다.

개념.문제 탭은 이번에 패치 하였습니다.

**Comment by parkbeomil** [comment]
넹 그르면 둘다 소수점 적용된버전으로 주시믄
제가 특정아이디만 api에서 예외처리해서 테스트하고
이슈없음 운영기 배포 후 api예외처리를 풀어서 
전체반영하는 방법으로 진행하는게 두번 작업 안하실거 같은데
어뗘셔요?

**Comment by Awesomeit-NSM** [comment]
네 CP님 소수점 적용된 버전으로 배포드리겠습니다.
