### ISSUE TITLE
스마트 배너 이슈

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#32]
스마트 강의
* https://app.only1.co.kr/lecture/getOnlyOneSmartBanner.asp?lectureListType=lectureDefault

경우 2개의 링크가 필요한데 설명 상이나 api상으로 list로 되어있습니다. 시나리오 상으로는 단순히 2개의 링크만 보면 되는데
뭔가 구조가 이상한듯 합니다.

물론 최상위 클래스 또한 마찬가지 입니다.
* https://app.only1.co.kr/lecture/getOnlyoneTopClassMain.asp?lectureListType=lectureTopMath

**Comment by jeongyeol-son** [comment]
![문의0](https://user-images.githubusercontent.com/66989039/208835506-84aa1044-cd7a-4985-9c0d-1e560a729f2b.PNG)
![문의1](https://user-images.githubusercontent.com/66989039/208835513-3525320b-f903-48e7-b653-d6fbf4feb071.PNG)

**Comment by parkbeomil** [comment]
요거는
각 api파일의 <bannerList>필드 하위에다가
스마트 배너는
```
<guideLink1>
<guideLink2>
```
두개,

최상위클래스 배너는
```
<guideLink1>
<guideLink2>
<guideLink3>
```
세개로 정리해놓았습니다.

**Comment by jeongyeol-son** [comment]
@Awesomeit-NSM  개발 확인하였습니다.

**Comment by Awesomeit-NSM** [comment]
앱단 확인 완료되었습니다.
