### ISSUE TITLE
학습 노트 생성 시 노트가 너무 많이 저장되었을 때 문제

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#33]
로그인 정보

*https://app.only1.co.kr/login/login.asp?userID=harueuki&userPWD=!s252125&deviceID=123&token=asdkk123kskf&osType=android&deviceType=phone&deviceModel=LG_FS320S&osVersion=android%204.4.2

*https://app.only1.co.kr/conceptSolving/setStudyNoteAction.asp?actionType=C&lp_idx=105561&l_idx=30762&ld_idx=5648330&noteTitle=&totalTime=4000

이 경우  반환 코드를 300으로 주시면 dialog를 띄웁니다. 200은 특수용도 목적의 코드입니다.

**Comment by parkbeomil** [comment]
반환코드 300에다가
메세지를 출력하도록 변경 했어요.
(갯수도 최대 500개로 조절해 놓았습니다.)

**Comment by jeongyeol-son** [comment]
@Awesomeit-NSM  개발 확인 하였습니다.

**Comment by Awesomeit-NSM** [comment]
앱단 확인 완료되었습니다.
