### ISSUE TITLE
학습노트 상세에서 이전 기록과 현재 기록을 비교하여 표시하는 부분에서 데이터 처리 오류

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#34]
로그인 정보
*https://app.only1.co.kr/login/login.asp?userID=harueuki&userPWD=!s252125&deviceID=123&token=asdkk123kskf&osType=android&deviceType=phone&deviceModel=LG_FS320S&osVersion=android%204.4.2

*https://app.only1.co.kr/conceptSolving/getStudyNoteTimeLine.asp?lp_idx=129208&l_idx=28862&LD_IDX=5171800&timeLectureIDX=987

위 API를 호출 하였을 때 외부 리스트의 데이터와 상세화면의 데이터에 이격이 있는 것으로 보입니다.

**Comment by parkbeomil** [comment]
네 확인하겠습니다.

**Comment by parkbeomil** [comment]
패치전에 테스트 데이터들하고
새로 정상적으로 잘 들어간 데이터들하고 섞여서 이상하게
보이는거 같아요. 초기화 하고 테스트 하겠습니다.

**Comment by parkbeomil** [comment]
요거 타임랩스를 이용해서 저장하고 나가는경우는 이슈 없는것 확인했습니다~

다만 새로 발견된 케이스 인데 일시정지 안하고
타이머가 계속 가고있는 상태에서 닫기를 누르면 저장할가요 물어보는데
의도적으로 늦게 누르면 백그라운드에서 시간이 가다가 최족 확인버튼
누르는 순간시간으로 저장되는거 같아요.
컨펌창이 뜰때 일시정지하고 창이 뜨면 될듯합니다.

**Comment by jeongyeol-son** [comment]
@parkbeomil  이 경우에 확인을 하면 그냥 나가면 되는데 취소일 경우 자동으로 리스타트를 해야하나요? 아니면 퍼즈 상태로 놔두고 사용자가 계속 버튼을 누르게 해야 하나요?

**Comment by parkbeomil** [comment]
네 매니저님~
그럴땐 걍 일시정시 상태로 두고 사용자가 선택
(다시하던지 진짜나가던지 )하게 하면 될듯합니다

**Comment by jeongyeol-son** [comment]
넵 . 처리 하겠습니다.

**Comment by Awesomeit-NSM** [comment]
앱단 확인 완료했습니다.
v5.3.9.00
