### ISSUE TITLE
온리원 스마트 학습 로그모드 활성화 방법

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#36]
@parkbeomil 

* 온리원 스마트 학습 로그 모드 활성화 방법

- 스마트학습 릴리즈 모드에서 로그 모드 오픈 기능을 추가하였습니다.
- 활성화 방법은 아래와 같습니다.

1. 통합검색 탭으로 이동
2. 검색 창에 "로그버전 켜짐"  이라고 입력 
3. 로그 오픈 
4. 앱내 로그를 보고 싶으면 tag를 SoobakC 라고 치시면 모든 앱내 디버깅 로그가 출력 됩니다.
5. api 연결을 보고싶으시면 filter에  OkHttp 혹은 api 연결만 보고 싶으시면 <-- 200 를 입력하시면 필터링 되어 동작합니다.

**Comment by parkbeomil** [comment]
네~ 알겠습니다. 감사합니다!!
