### ISSUE TITLE
api파일명 질문있어요

### ISSUE THREAD

**Issue by parkbeomil** [awesomeitdev/onlyonemiddle#37]
강좌수강을 위한 강의목록 페이지에서
상단에 학습진도율 표시하는 부분중에서
우측상단(getLectureConceptProcess.asp) 옆에 강의 탭에잇는
정보들을 불러오는 api 위치좀 알려주세요~
제가 두개를 똑같이 찍어놓은거같아서 수정하려고하는데
어딘지 못찾겠어요. ㅠ.ㅠ

**Comment by jeongyeol-son** [comment]
* https://app.only1.co.kr/myPage/getMyLectureInfo.asp?lp_idx=105561&lh_idx=10942055 
* https://app.only1.co.kr/myPage/getMyLessonList.asp?lp_idx=105561&lh_idx=10942055 
* https://app.only1.co.kr/conceptSolving/getLectureConceptProcess.asp?lp_idx=105561&l_idx=30762 
해당 메뉴에서 불러오는 api 입니다.

**Comment by parkbeomil** [comment]
![20221221_224627.jpg](https://user-images.githubusercontent.com/11604271/208919967-dab52d11-b09f-4c86-80cf-de7d77f53199.jpg)

**Comment by parkbeomil** [comment]
네~ 감사합니다~

한가지만 더 여쭤볼게요.
위에 사진에서 1,2번 두개가 같은값으로 움직이는거 같아요~

/myPage/getMyLectureInfo.asp에서
readCount가 1번(내가수강한강 수)
recommendCount가 2번(권장강 수)

로 해주시면 될듯합니당~

**Comment by jeongyeol-son** [comment]
네 알겠습니다.

**Comment by Awesomeit-NSM** [comment]
앱단 확인 완료했습니다.
v5.3.9.00
