### ISSUE TITLE
v5.3.9배포에서 타이머 관련 적용이 안된것 같습니다.

### ISSUE THREAD

**Issue by parkbeomil** [awesomeitdev/onlyonemiddle#39]
매니저님 안녕하세요~
늦게까지 작업해주셨는데 타이머 부분 적용이 잘 안된것 같아요.

게이트페이지서 타이머 저장이나 종료관련해서 컨펌창이 뜰때 타이머가 멈춰서
바로저장하든 한참잇다 하던 타이머 뜰때 시간이 그대로 있으면 되는데
현재는 시간이 계속 흘르고 있는것 같습니다.(화면표시, 디비저장 모두 시간이 흐르는거 같아요)

그리고 가끔나타나는 현상인데, 공부노트에서 첫 구간 기록 랩 00초 가 아닌 실제 타이머 시간과
같은값이 찍힐때가 있는것 같습니다. 이것도 한번 확인부탁드려요.

감사합니다.

**Comment by jeongyeol-son** [comment]
* 타이머 상세 기록 띄울 시 "상세화면을 확인 하시겠습니까?" 문구 변경 
* 저장하기 누를 시 "학습한 시간을 저장하시겠습니까?"

**Comment by jeongyeol-son** [comment]
위 부분 적용하여 배포 했습니다.

**Comment by jeongyeol-son** [comment]
그리고 가끔나타나는 현상인데, 공부노트에서 첫 구간 기록 랩 00초 가 아닌 실제 타이머 시간과
같은값이 찍힐때가 있는것 같습니다. 이것도 한번 확인부탁드려요. -> 확인 결과 첫구간이 실제 타이머 시간과 같은 값이 찍혀야되는듯 합니다.

**Comment by KwonGeneral** [comment]
[계정: harueuki]
https://app.only1.co.kr/conceptSolving/getStudyNoteTimeLine.asp?lp_idx=110636&l_idx=31528&LD_IDX=5928440&timeLectureIDX=1437

해당 API를 보시면, 구간기록 리스트에서 첫 번째 인덱스의 [ timeLineDistanceTime ] 해당 필드가 [ timeLineCurrentTime ] 이 필드와 같은 값이 아닌, 00분00초로 찍혀있습니다.
정상적인 코드는, 구간기록 리스트의 첫 번째 인덱스는 [ timeLineCurrentTime ] [ timeLineDistanceTime ] 이 2개의 필드가 값이 서로 동일해야합니다.
확인 부탁드립니다~~
@parkbeomil

**Comment by parkbeomil** [comment]
네~  
확인해서 처리해놓았어요.
@KwonGeneral @jeongyeol-son 

감사드려요.
