### ISSUE TITLE
수강중인 강좌 상세>강의 목록(SB문서 7페이지 5번) 

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#4]
학습하기 버튼 클릭 시, 게이트 페이지 노출은 어떤 값을 플래그로 보면 될까요?

>박범일(비상)
api목록에 isGateView 필드 만들어서 1:노출, 0:비노출 로 찍겠습니다.

**Comment by parkbeomil** [comment]
api목록에 isGateView 필드 만들어서 1:노출, 0:비노출 로 찍겠습니다. (현재는 0으로 하드코딩해놓은 상태입니다.)
`<isGateView>0</isGateView>	<!-- 개념문풀 존재여부 (0: 비노출, 1: 노출)-->`

**Comment by KwonGeneral** [comment]
확인했습니다.
