### ISSUE TITLE
강사 비공개 또는 질답게시판 비공개시 버튼 예외처리

### ISSUE THREAD

**Issue by KwonGeneral** [awesomeitdev/onlyonemiddle#40]
요청
- 강사 비공개 처리 시-> 강사 홈버튼 아이콘 예외처리
https://app.only1.co.kr/lecture/getLectureInfo.asp 
<teacherOpenYN><![CDATA[Y Or N]]></teacherOpenYN>        
- 강사 질답 이용여부에 따른 게시글 버튼 노출
https://app.only1.co.kr/myPage/questionboard/getTeacherQuestionList.asp 
<isUseQuestionboard><![CDATA[1 Or 0]]></isUseQuestionboard> 

---
답변
1. 현재 API에서 [ 수강중인강좌>강의목록 ] 페이지에서 [ 선생님 ] 부분은 
"https://app.only1.co.kr/myPage/getMyLectureInfo.asp" 해당 API를 통해서 
데이터를 가져오고 있습니다.
[ teacherOpenYN ] 필드는 해당 API에 추가해주실 수 있을까요? 

2. 또한,[ "](https://app.only1.co.kr/myPage/getMyLectureInfo.asp)https://app.only1.co.kr/myPage/questionboard/getTeacherQuestionList.asp" 
해당 API에서 들어오는 [ isUseQuestionboard ] 필드를 통해서 
[ 수강중인강좌>질답게시판 ] 페이지는 처리가 가능하지만, 
[ 수강중인강좌>강의목록>선생님>학습 질답 ] 페이지는 
"https://app.only1.co.kr/teacher/getTeacherQuestionList.asp" 해당 API를 통해서 데이터를 
받아오고 있기 때문에, 해당 API에도 [ isUseQuestionboard ] 필드를 
추가해주실 수 있을까요?

**Comment by leejh18Visang** [comment]
https://app.only1.co.kr/myPage/getMyLectureInfo.asp?lp_idx=85915&lh_idx=10953016
https://app.only1.co.kr/teacher/getTeacherQuestionList.asp?t_mem_ID=mteach73&currentPage=1&searchType=&searchString=&isMyQuestion=0

해당 URL에 추가해놨습니다.
확인하고 이슈있으시면 얘기해주세요~~

**Comment by Awesomeit-NSM** [comment]
API확인했으며 현재 테스트중입니다

**Comment by Awesomeit-NSM** [comment]
앱단 확인 완료 후 배포했습니다.
v5.4.2.00

**Comment by jeongyeol-son** [comment]
@leejh18Visang @parkbeomil 

https://app.only1.co.kr/myPage/questionboard/getTeacherQuestionList.asp?t_mem_ID=mteach73&currentPage=1&searchType=b_Content&searchString=&isMyQuestion=0&LP_IDX=85915

api의 경우  현재 
![캡처_00](https://user-images.githubusercontent.com/66989039/209892456-8bbdad5c-e441-461c-9aec-94e7adfdaaa0.PNG)
위와 같이 들어오고 있습니다.

위와 같은 구조는 구조 상 저희 쪽에서 분석 자체를 할 수 없는 구조 이며, 아래의 구조와 같이 바꿔주세요.
<isUseQuestionboard>
<![CDATA[ 1 ]]>
</isUseQuestionboard>

해당 부분을 상위로 이 관

<currentPage>1</currentPage>
<hasMore>1</hasMore>
<isUseQuestionboard>
<![CDATA[ 1 ]]>
</isUseQuestionboard>


위와 같이 바꿔주시면 됩니다.

그리고 문제는 다른 쪽 api
* https://app.only1.co.kr/teacher/getTeacherQuestionList.asp?t_mem_ID=mteach73&currentPage=1&searchType=&searchString=&isMyQuestion=0

이 API 인데. 이 부분은 뭔가 이상하지만 이 부분에서는 LIST DATA를  <teacherQuickList> 라는 이름으로 받고 있어 정상 작동 하게 되어있습니다. 구지 안건드리셔도 될 듯 합니다.

이상입니다.

**Comment by parkbeomil** [comment]
매니저님

getTeacherQuestionList.asp파일에 아래와 같이 추가해 놓았습니다.

(0,1 번갈아가면서 확인해봤는데 버튼은 계속 활성화 되는거 같아요)

```

<currentPage>1</currentPage>
<hasMore>0</hasMore>

<isUseQuestionboard>0</isUseQuestionboard>
```

**Comment by leejh18Visang** [comment]
leejh18 / 01033580937a! <-- App 해당 아이디로 로그인하시면 됩니다.
플래그값 변하는 거 확이나고싶으시면 전화주시면 바로 바꿔놓고 원복하고 이런식으로 해야될것같습니다~~
