### ISSUE TITLE
수강중인강좌 상세>강의 상세 아이콘 설명 추가

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/onlyonemiddle#44]
참고 문서 : #41
개념콕, 문제콕을 지원하는 강좌의 경우, '개념콕, 문제콕 강의 목록 이용 방법' 을 표기하고 해당 영역 탭시 웹뷰 페이지를 호출해달라는 내용입니다.
![image](https://user-images.githubusercontent.com/70569321/210192725-d5f0507b-ddc8-41e1-9257-ca0c21fd7520.png)

**Comment by Awesomeit-NSM** [comment]
웹뷰 팝업으로 구현 가능합니다.
API전달을 부탁드립니다.

**Comment by Awesomeit-NSM** [comment]
디자인 파일을 받아 제플린에 업로드했습니다.

**Comment by jeongyeol-son** [comment]
@parkbeomil  해당 부분 API 혹은 URL 요청 드립니다.

**Comment by parkbeomil** [comment]
/lecture/getLessonList.asp파일에
isConceptSolivng (개념문풀 이용방법 존재여부 (1:존재, 0:없음))
conceptSolivngGuideURL ( 개념문풀 이용방법 안내 주소)
두개 필드 추가 했습니다.

**Comment by Awesomeit-NSM** [comment]
해당 내용 적용 확인했으며 배포 후 클로즈하겠습니다.

**Comment by Awesomeit-NSM** [comment]
v5.4.7.00 정상 배포 했습니다.
