### ISSUE TITLE
플레이어 [이어보기] 기능 확인(개념콕,문제콕)

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/onlyonemiddle#46]
참고 문서 : #41
플레이어 '이어보기' 옵션을 켠 상태에서 개념콕, 문제콕 영상의 이어보기를 지원해달라는 내용입니다.
관련해 작업이 가능할지 검토를 부탁드립니다.

**Comment by jeongyeol-son** [comment]
@parkbeomil  API 지원 유무 확인이 필요합니다.  
mypage/getStreamingMovieInfo.asp api에서 개념/문제콕 별로 이어보기 저장값 반환을 별도로 할 수 있는지 파악 부탁드리겠습니다.
그리고 저장 시 api (myPage/setStudyTime.asp)에서도 해당 기능을 지원하기위한 파라메터가 추가 되어야 할 듯 보입니다.

검토 해 보시고 가이드 부탁드립니다.

**Comment by parkbeomil** [comment]
게이트페이지(getConceptProcess.asp)에서 
ConceptInfo 아래에 lastConceptIDX와
SolvingInfo 아래에 lastSolvingIDX를 추가해서
마지막으로 저장한 개념,문제 idx를 추가하겠습니다.
해당 버튼 누를때 "이어서 수강하시겠습니까?" 정도의 
컨펌박스 출력하면 될듯한데 의견 부탁드립니다.

**Comment by parkbeomil** [comment]
컨펌메세지를 

이전 학습시 종료한 구간의 콕강의 부터 재생할까요? 
아니오를 선택시 처음부터 재생됩니다.
[네 ][아니요]


요내용으로 찍는것으로 부탁드립니다.

**Comment by Awesomeit-NSM** [comment]
@parkbeomil CP님 말씀주신 내용 확인했습니다.
추가로, lastConceptIDX, lastSolvingIDX가 없는 경우(해당 강의의 콕강의를 들은 기록이 없는 경우)에는 팝업을 띄우지 않고 첫번째 콕강의를 플레이하도록 하겠습니다.

**Comment by parkbeomil** [comment]
> @parkbeomil CP님 말씀주신 내용 확인했습니다.
> 추가로, lastConceptIDX, lastSolvingIDX가 없는 경우(해당 강의의 콕강의를 들은 기록이 없는 경우)에는 팝업을 띄우지 않고 첫번째 콕강의를 플레이하도록 하겠습니다.

맞습니당~ 감사드려요~~~

**Comment by Awesomeit-NSM** [comment]
해당 내용 적용 확인했으며 배포 후 클로즈하겠습니다.

**Comment by Awesomeit-NSM** [comment]
v5.4.7.00 정상 배포 했습니다.

**Comment by Awesomeit-NSM** [comment]
아래와 같이 유저 설정의 '이어보기' 값과 연동해달라는 요청을 받았습니다.

- 팝업은 이어보기가 켜있을때만 노출되고 꺼진 상태인 경우는 그냥 얼럿 노출 없이 처음부터 재생

**Comment by Awesomeit-NSM** [comment]
해당 내용 반영 확인했습니다.
앱 배포 후 클로즈하겠습니다.

**Comment by Awesomeit-NSM** [comment]
'이어보기' 값이 OFF인 상태에서 처음부터 재생은 잘 동작되나, 인덱스 창의 포커스에 문제가 있다고 합니다.
(Ex. 이어보기OFF상태 > 1~5 인덱스가 있는 콕강의에서 3번째 강의를 듣고 종료 > 콕강의 재생 > 처음부터 강의 재생은 되나 인덱스 포커스가 3번째로 표시됨)

**Comment by Awesomeit-NSM** [comment]
해당 현상을 수정해 v5.5.0.00 을 배포했습니다.
