### ISSUE TITLE
학습타이머>구간기록 삭제 기능 복원

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/onlyonemiddle#48]
참고 문서 : #41
학습타이머>구간기록 삭제 기능을 복원해달라는 내용입니다.
관련해 작업이 가능할지 검토를 부탁드립니다.

**Comment by Awesomeit-NSM** [comment]
구간기록 삭제의 경우 API기능 동작의 검토가 필요할 것 같은데 의견을 한번 부탁드립니다.
@parkbeomil

**Comment by parkbeomil** [comment]
플레이어창에서 제어는 기존 로직들을 다 원복해야해서 어려울듯하고
공부노트 리스트에서 구간기록내역 수정하는 부분에서만 적용하는것으로
조정하였습니다.(getStudyNoteTimeLine.asp, setStudyNoteAction.asp)

**Comment by parkbeomil** [comment]
4-x. 에 파라메타 actionType, timeDetailIDX, timeLectureIDX 전달주시면 될듯합니다.
(setStudyTimerAction.asp에는 아직 저장안하고 작업만 해놨어요.)

**Comment by Awesomeit-NSM** [comment]
@parkbeomil CP님 말씀주신 내용 확인했습니다.
개발 작업 진행하면서 질문 생기면 연락 드리겠습니다.

**Comment by parkbeomil** [comment]
네 알겠습니다. (setStudyTimerAction.asp 요기도 작업해서 저장해 놓았습니다.)

**Comment by Awesomeit-NSM** [comment]
해당 내용 반영 확인했으며 배포 후 클로즈하겠습니다.

**Comment by Awesomeit-NSM** [comment]
v5.4.7.00 정상 배포 했습니다.

**Comment by Awesomeit-NSM** [comment]
구간 기록 삭제(X) 버튼 탭시 표출되는 팝업 문구를 아래와 같이 변경해 달라는 요청을 받았습니다.

구간 기록 삭제는 [수정 취소]를 해도 복구가 불가능 합니다.
삭제하시겠습니까?

**Comment by Awesomeit-NSM** [comment]
해당 내용 반영 확인했습니다.
앱 배포 후 클로즈하겠습니다.

**Comment by parkbeomil** [comment]
수정 후 저장하기 누를때 totalTime값이 없어서 0으로 들어갔습니다.
저장시 totalTime체크해서 0보다 큰값일때만 시간 없뎋하도록 처리해서
시간사라지는 이슈 처리하였습니다.
