### ISSUE TITLE
플로팅배너 추가

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/onlyonemiddle#49]
참고 문서 : #41
스마트강의, 최상위클래스 메뉴 내에 플로팅 배너를 추가해달라는 내용입니다.
※정확한 메뉴 위치는 답변을 받는대로 코멘트에 남기겠습니다.

**Comment by Awesomeit-NSM** [comment]
플로팅 배너 위치는 스마트강의 메뉴 전체(공통), 최상위클래스 메뉴 전체(공통) 입니다.

**Comment by Awesomeit-NSM** [comment]
플로팅 배너 위치값과 사이즈값이 필요해 화면 디자인을 부탁드립니다.

**Comment by Awesomeit-NSM** [comment]
디자인 파일을 받아 제플린에 업로드했습니다.

**Comment by jeongyeol-son** [comment]
@parkbeomil  해당 부분 API 혹은 URL 요청 드립니다.

**Comment by parkbeomil** [comment]
/lecture/getOnlyoneTopClassMain.asp, /lecture/getOnlyoneSmartBanner.asp 파일에
main.asp에서 처럼 floatingBannerInfo 필드 하위로 정보 추가 하였습니다.

**Comment by Awesomeit-NSM** [comment]
해당 내용 적용 확인했습니다.
현재 X버튼이 포함된 이미지가 적용되어 있는데 이부분은 배포시 안내하겠습니다.

**Comment by Awesomeit-NSM** [comment]
v5.4.7.00 정상 배포 했습니다.
