### ISSUE TITLE
학습이력(SB문서 8페이지)

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#5]
nexthas값 주실 수 있을까요.

>박범일(비상)
가능할것 같습니다.

**Comment by parkbeomil** [comment]
추가 하였습니다. (nexthas랑 호환성차원에서 기존에쓰던 필드랑 같은 이름인 hasMore도 같은값으로 넣어놨습니다.)
```
<nexthas>1</nexthas>
<hasMore>1</hasMore>
```

**Comment by KwonGeneral** [comment]
확인했습니다. hasMore로 사용하겠습니다.
