### ISSUE TITLE
메타인지학습>웹뷰팝업 버튼 추가

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/onlyonemiddle#50]
참고 문서 : #41
메인인지학습 우측상단 영역에 '영상으로 미리 보기' 버튼 추가, 탭시 웹뷰 호출이 필요합니다.
이미지 파일과 API는 받는대로 공유드리겠습니다.
![image](https://user-images.githubusercontent.com/70569321/210203545-7527f1fd-020d-4035-aed3-788709b633c7.png)

**Comment by Awesomeit-NSM** [comment]
디자인 파일을 받아 제플린에 업로드했습니다.

**Comment by jeongyeol-son** [comment]
@parkbeomil  해당 부분 API 혹은 URL 요청 드립니다.

**Comment by parkbeomil** [comment]
얘는 아에 페이지가 없던거라
열공레이스 배너 체크하는것과 동일하게
main.asp에 whatIsMetaRecognition 아래에 mediaURL 요기다가 
영상주소 추가 했는데 괜찮을가요?

**Comment by jeongyeol-son** [comment]
@parkbeomil  혹여 mediaURL 이 영상주소인가요? 영상이 플레이되는 page주소인가요? page 영역이야 어디에 하셔도 상관은 없습니다만. main.asp 쪽에서 처리하는 데이터가 많은데, 부하는 괜찮으신가요? 메타 들어갈 때마다 호출 할듯한데 말이죠.

**Comment by parkbeomil** [comment]
> 

넹 따로 하는게 더 좋을거 같아요~
/aboutMetaRecognition/getMediaInfo.asp
파일에 동일하게 whatIsMetaRecognition > mediaURL 욜케 만들어놨습니다
말씀감사드려요~.

**Comment by Awesomeit-NSM** [comment]
해당 내용 적용 확인했으며 배포 후 클로즈하겠습니다.

**Comment by Awesomeit-NSM** [comment]
v5.4.7.00 정상 배포 했습니다.
