### ISSUE TITLE
메인>열공레이스 포인트 적립 아이콘 추가

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/onlyonemiddle#51]
참고 문서 : #41
출석 여부에 따라 열공레이스 위에 포인트 적립 애니메이션 아이콘 배치가 필요합니다.
출석 체크를 안할 경우 애니메이션 동작, 출석 체크를 했을 경우 모션 없음으로 동작이 필요합니다.
관련해 출석 체크 여부 API와 디자인 파일이 필요하며, 받는대로 공유드리겠습니다.
![image](https://user-images.githubusercontent.com/70569321/210203380-180f79d3-ad7e-4dc8-b823-99bcf8834cc8.png)

**Comment by Awesomeit-NSM** [comment]
디자인 파일을 받아 제플린에 업로드했습니다.

**Comment by parkbeomil** [comment]
기존 베너 체크하는곳(/main.asp)에 floatingBannerInfo4Race 로 추가 했습니다.
항목은 floatingBannerInfo 와 동일한 구조로 추가했어요.
일단 이미지는 진단평가 것으로 추가해놓았습니다.
위치는 겹치지 않게 적당히 비켜서 찍어주시면 될듯해요.

**Comment by jeongyeol-son** [comment]
@parkbeomil 해당 기능은 오늘 출석 여부(Y/N : istodayAttendChk) 과 출석을 눌렀을 때 띄울 URL만 있으면 될듯합니다.
floatingBannerInfo는 필요 없을 듯 하네요. attendUrl 만 istodayAttendChk과 동일 레이어에 둬 주세요.

**Comment by parkbeomil** [comment]
넵 알겠습니다~
istodayAttendChk 바로 아래에 isStudyRaceBanner 추가 하였습니다. (1:노출, 0:비노출)

**Comment by leejh18Visang** [comment]
app.only1.co.kr/main.asp
해당 링크  (1:노출, 0:비노출) 로 추가해놨습니다.
그리고 확인이 필요한 부분이 있는데, 
 - 상단 GNB 부분 나의 활동/결제 -> 열공레이스 
 - 메인화면 -> 열공레이스
 
 --> 해당 부분 웹뷰로 받아오는 API 주소좀 확인할 수 있을까요?
 
 Ex> 메인화면 플로팅 진단평가 링크API주소
  app.only1.co.kr/main.asp (floatingAppLink 파라미터컬럼)
 이런식으로 부탁드립니다.

**Comment by jeongyeol-son** [comment]
@leejh18Visang  열공 레이스 URL은 /motivateZone/index.asp 으로 반환됩니다.
다만 제 쪽에서 기획을 착각하여, 추가적인 요청을 하였고, 별도의 URL 반환은 필요 없을 듯 보입니다.

현행 작업 해 주신 수준으로도 구현되었습니다.

**Comment by Awesomeit-NSM** [comment]
v5.4.7.00 정상 배포 했습니다.
