### ISSUE TITLE
메타인지 학습앱 호출관련 패키지명 변경

### ISSUE THREAD

**Issue by Awesomeit-NSM** [awesomeitdev/onlyonemiddle#53]
메타인지 학습앱에서 싸인키를 잃어버린 관계로 부득이 패키지명을 변경이 필요하다는 요청입니다.

금요일(2023.01.13) 배포버전에 적용을 요청 받았으며 변경되는 패키지 네임은 아래와 같습니다.

com.visang.onlyone => com.visang.only1meta

**Comment by parkbeomil** [comment]
바쁘실텐데 요런 일까지 생깁니다. 죄송합니다. ㅠ.ㅠ

**Comment by Awesomeit-NSM** [comment]
패키지네임이 변경된 완공앱 다운로드 링크입니다.
https://drive.google.com/file/d/1Q7aOkRiJjG0GavCEgibHogkrxgsR7-bM/view?usp=drive_web

**Comment by Awesomeit-NSM** [comment]
패키지네임 변경 및 앱 호출 확인했습니다.
다만 완공앱 호출 후 여러번 호출이 되는 듯한 동작이 있어 이부분은 완공앱에서 확인이 필요할 것 같습니다.

**Comment by Awesomeit-NSM** [comment]
v5.4.7.00 정상 배포 했습니다.
