### ISSUE TITLE
개념콕 및 문제콕 플레이어 종료 시, 타이틀에 [총 **개의 개념 콕 or 문제 콕을 학습하셨습니다.] 에서 **개를 학습종료 API에서 줘야합니다.

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#6]
https://a1.only1.co.kr/soobakcPlayer/getLectureEndInfo.asp

>박범일(비상)
etLectureEndInfo.asp내에 아이템 추가해놓겠습니다.qockType1=100, qockType2=40 이런식으로

**Comment by parkbeomil** [comment]
getLectureEndInfo.asp내에 아래값으로 추가했습니다. (현재는 99로 하드코딩해놓은 상태입니다.)
```
<qockType1Count>99</qockType1Count> <!-- 학습한 개념콕 카운트 -->
<qockType2Count>99</qockType2Count> <!-- 학습한 문제콕 카운트 -->
```

**Comment by KwonGeneral** [comment]
확인했습니다.
