### ISSUE TITLE
학습입시 전략 및 기타 수정건(2023-03-09)

### ISSUE THREAD

**Issue by leejh18Visang** [awesomeitdev/onlyonemiddle#60]
#환경설정
app.only1.co.kr/system/setConfig.asp (환경설정 변경하기)
app.only1.co.kr/system/getConfig.asp (환경설정 보기)
<play_intro><![CDATA[<%=play_intro%>]]></play_intro>

#영상스트리밍 정보
app.only1.co.kr/myPage/getStreamingMovieInfo.asp
<play_intro><![CDATA["&play_intro&"]]></play_intro>
<introFileLink><![CDATA["&introFileLink&"]]></introFileLink>

#성적우수 장학생
harueuki 권한풀어서 해당 탭 사용가능
app.only1.co.kr/myPage/gradeShip/getChallengeInfo.asp (날짜조절)
app.only1.co.kr/myPage/gradeShip/getStep2Info.asp (familyCertificate-> 가족관계증명서)
app.only1.co.kr/myPage/gradeShip/setStep2Action.asp (폼 테스트 가능)
 https://app.only1.co.kr/apiList.asp -> 성적장학생 도전 -> 2단계 신청하기 폼 설정가능
harueuki
도전차수IDX[evIDX] = 57
나의 신청정보IDX[myInfoIDX] = 121463
입력 후, 테스트 가능

#학습입시정보
https://app.only1.co.kr/knowledge/getOnlyoneIndex.asp
특목고합격수기 / 입시전략보고서 / 합격사례 UPDATE  이런식으로 찾아서 컬럼찾으면 됨

#입시전략보고서 & 특목고합격수기
해당 데이터 클릭 시 -> 전체 웹뷰 팝업 필요 
Ex> 공부덕후 TV 
경로는 업데이트 예정

관련 문의사항은 직접 연락주거나 아래 남겨주시면 됩니다. (이종화cp)

**Comment by leejh18Visang** [comment]
#입시전략보고서 & 특목고합격수기
https://webview.only1.co.kr/Knowledge/interview/index.asp
https://webview.only1.co.kr/Knowledge/edu_info/index.asp
해당 부분 웹뷰 작업완료
전체 팝업 패치 및 영상도 나와야합니다.
Ex> 공부덕후 TV

**Comment by Awesomeit-NSM** [comment]
네 CP님 내용 확인했습니다.
작업 진행하겠습니다~

**Comment by KwonGeneral** [comment]
기존 공부덕후 TV처럼 전체 팝업 패치 및 영상 처리를 하기 위해서는
해당 컨텐츠 클릭시 주는 uri를 공부덕후 TV처럼
[ soobakcdialog://showdialog?title=제목&url=https://link ]
위 처럼 작업해서 주셔야 처리가 가능합니다~!

**Comment by leejh18Visang** [comment]
넵 확인했습니다. 
하나 궁금한 부분이 있는데
학습,입시전략 메인화면에서
특목고 ZONE -> 합격사례UPDATE 버튼이 있습니다.
해당 버튼을 누르면 팝업이 안뜨고 전체화면이 나오고 있습니다.
성적우수후기처럼  전체팝업이 나와야합니다.


API URL : https://app.only1.co.kr/knowledge/getOnlyoneIndex.asp


<purposeZoneBestURL>
<![CDATA[ https://webview.only1.co.kr/special_purpose_zone/passCaseHisotryWebview.asp?memberID=leejh18&gcPassStoryIDX=75 ]]>
</purposeZoneBestURL>


<webViewURL>
<![CDATA[ https://webview.only1.co.kr/Knowledge/sbcScholar/view.asp?idx=1907&userID=leejh18 ]]>
</webViewURL>

위처럼 동일하게 처리했는데
확인해보시고 저희쪽 확인 필요한 부분있으면 연락주시면 됩니다.

감사합니다.

**Comment by leejh18Visang** [comment]
![image](https://user-images.githubusercontent.com/108122184/225554099-6a9994ea-dbe0-4bea-8b69-d10bf31934cc.png)

**Comment by leejh18Visang** [comment]
> 특목고 합격수기
입학학교+합격 컬럼 추가
<schoolType><![CDATA[<%=schoolType&" 합격"%>]]></schoolType>
현재시간기준 오픈된 리스트 3개라서 API 3개 보내고있는데, 리스트가 중간에 공백현상이 발생하는데
한번 확인 부탁드립니다.

> 입시전략보고서
팝업창 URL
<topAppMainURL><![CDATA[https://webview.only1.co.kr/knowledge/edu_info/detailWebview.asp?memberID=<%=userID%>&topSeq=<%=topSeq%>]]></topAppMainURL>
메인 리스트 URL
<topAppMainListURL><![CDATA[https://webview.only1.co.kr/knowledge/edu_info/index.asp?memberID=<%=userID%>]]></topAppMainListURL>
특목고 학교생활 메인 LIST
기존 GNB 영역 학습입시전략 -> LNB 특목고 리얼 학교 생활 부분 연결해주면 될 것 같습니다.

확인필요한 부분있으면 연락주시면 됩니다.
감사합니다.

**Comment by leejh18Visang** [comment]
> 특목고 합격수기
입학학교+합격 컬럼 추가
<schoolType><하나고합격></schoolType>
현재시간기준 오픈된 리스트 3개라서 API 3개 보내고있는데, 리스트가 중간에 공백현상이 발생하는데
한번 확인 부탁드립니다.

> 입시전략보고서
팝업창 URL
<topAppMainURL><urlAddress></topAppMainURL>
메인 리스트 URL
<topAppMainListURL><urlAddress></topAppMainListURL>
특목고 학교생활 메인 LIST
기존 GNB 영역 학습입시전략 -> LNB 특목고 리얼 학교 생활 부분 연결해주면 될 것 같습니다.

**Comment by leejh18Visang** [comment]
![image](https://user-images.githubusercontent.com/108122184/225555374-397eab09-9a9c-4971-b9cf-2a0af61a8f6c.png)

위의 이미지 같이보면 될 것 같습니다. (텍스트 자꾸 깨져서 이미지 캡처해서 보내드립니다)

**Comment by KwonGeneral** [comment]
완전학습 솔루션은 텍스트 사이즈를 늘린 이미지를 적용 완료했습니다.
특목고 합격 사례의 경우, 클릭 시, [학습입시전략>공부덕후TV>리스트아이템클릭] 나오는 웹뷰 처럼 팝업 형태로 처리하도록 변경했습니다.

**Comment by KwonGeneral** [comment]
[ 특목고 합격 수기 ]
- 이미지 해상도: 해당 부분은 속도 이슈로 인해 이미지 사이즈를 Fit하게 잡아놨었는데, 이번에 사이즈 조정하면서 해당 부분에 관한 수정이 빠져있었습니다. ( 수정완료 )
- 학교 이름: API에서 schoolType 필드 가져와서 적용했습니다. ( 수정완료 )

[ 입시 전략 보고서 ]
- 해당 영역 클릭 시, [ topAppMainURL ] 필드 값에 따라 웹뷰 띄우도록 변경했습니다. ( 수정완료 )

[ 특목고 리얼 학교 생활 ]
- 해당 영역 클릭 시, 학습입시전략 페이지로 메뉴 이동 하도록 변경 했습니다. ( 수정완료 )

[ 성적 우수수기 ]
- 베스트 수기: 해당 부분은 "https://app.only1.co.kr/knowledge/getOnlyoneIndex.asp" API를 통해서, scholarList 필드를 통해 가져오고 있습니다. 확인해보니 해당 리스트에서 가장 최신 5개 글을 주고 있습니다. 해당 필드에 베스트 수기 리스트를 던져주시면 제대로 적용이 될 것 같습니다.

**Comment by leejh18Visang** [comment]
- 열공편의점 링크 
메인 상단에 실시간학습질문 & SKY 멘토상담 & 장학생 도전 & 열공편의점
이렇게 4개 링크가 있는데
열공 편의점 관련해서 링크 전달해드립니다.
app.only1.co.kr/main.asp
	
		<studyStore>
			<studyStorelink><![CDATA[https://webview.only1.co.kr/appContentsTest/studyrace/index.asp?goStore=Y&userid=<%=userID%>]]></studyStorelink> 
		</studyStore>
	

이 부분에 일단올렸고, 해당 영역 링크 따로 모아둔 페이지 있으면 공유해주시면 그쪽으로 수정해놓겠습니다.

**Comment by leejh18Visang** [comment]
PW : 74A7106E

**Comment by leejh18Visang** [comment]
성적 우수수기  베스트 수기 부분은 확인했습니다. 데이터 잘나옴

**Comment by KwonGeneral** [comment]
기존 열공레이스의 경우에 [ https://app.only1.co.kr/motivateZone/index.asp ]
해당 API에서 guideURL 필드로 받아온 링크로 웹뷰를 띄우고 있습니다.

해당 API에 열공레이스, 열공편의점 필드를 2개 만들어서 주시면 될 것 같습니다.

**Comment by leejh18Visang** [comment]
harueuki : 99607A67 (테스트계정)

**Comment by Awesomeit-NSM** [comment]
학습입시전략 서브메인 수정을 진행해 v5.6.2.00 앱을 메일로 배포드렸습니다.
해당 이슈는 클로즈하겠습니다.
