### ISSUE TITLE
메타인지학습앱 연동시 유니코드문자 표시관련

### ISSUE THREAD

**Issue by parkbeomil** [awesomeitdev/onlyonemiddle#61]
노메니저님 안녕하세요~

텍스트 표시관련 문의드릴것이 있습니다.

메타인지학습 연동시 api로 메타인지Db에서 데이터를 받아다가
저희 api에 그대로 출력하게 되어있는데 텍스트중에 일부 특수문자(수식기호)들이
유니코드로 디코딩 되서 표시가 되고 있어서 해당 텍스트를 원래 문자로 표시가
가능할지 문의 드립니다.

ex) 
- 원래 문장 : 이차함수 y=ax²의 그래프 
- 출력되는 문장 : 이차함수 \uD835\uDC66=\uD835\uDC4E\uD835\uDC65²의 그래프

**Comment by Awesomeit-NSM** [comment]
@jeongyeol-son 매니저님 확인을 한번 부탁드립니다~

**Comment by jeongyeol-son** [comment]
일단 저도 정확 하게는 모르겠는데 

String input = "이차함수 \\uD835\\uDC66=\\uD835\\uDC4E\\uD835\\uDC65²의 그래프";
String output = input.replaceAll("\\\\u([0-9a-fA-F]{4})", "\\\\x{$1}");
System.out.println(output);

이렇게 한번 처리해 보시겠어요?

**Comment by parkbeomil** [comment]
제가 구글링이랑 여기저기좀 문의해봤는데
자바에서 utf16으로 내부 코드처리를 하는데
저희랑 연동시 브라우저가 자동으로 디코딩(한글 디코딩하듯이)해서 
그런거 같다고 하네요.

예를들어 식에서 𝑦값은 
- 화면표시 : 𝑦 (수학적 기울임 꼴 작은 Y)
- UTF-16BE(자바코드) : D8 35 DC 66
- 유니코드 : 1D466
- htmlcode: &amp;#119910;
이렇게 표현된다고 합니다.

저희는 utf-16be로 넘겨주는값을 인식하지 못해서 \uD835\uDC66 이렇게
받아내고 있는거 같습니다.

문의드린부분은  \uD835\uDC66 이거를  제가 D835 DC66 요렇게 변환해서 넘겨드리면 
자바에서 원래값인 𝑦요거로 치환이 가능할지 문의드렸어요.

수식이라 이게 처리가 어케 애매하네요.

한번만더 확인 부탁드립니다. 감사합니다.

**Comment by KwonGeneral** [comment]
1. 이차함수 \uD835\uDC66=\uD835\uDC4E\uD835\uDC65²의 그래프
2. String input = "이차함수 \uD835\uDC66=\uD835\uDC4E\uD835\uDC65²의 그래프";
String output = input.replaceAll("\\u([0-9a-fA-F]{4})", "\\x{$1}");
System.out.println(output);

위 1번과 2번 모두 정상적으로 "이차함수 𝑦=𝑎𝑥²의 그래프" 으로 표출이 됩니다.

단, D835 DC66 이렇게 변환해서 넘겨주시면 처리하기가 애매합니다.
"이차함수 \uD835\uDC66=\uD835\uDC4E\uD835\uDC65²의 그래프" 이 문구 그대로 주시면 됩니다.

**Comment by Awesomeit-NSM** [comment]
테스트계정 span26 / 2
오늘의 메타학습(메인)>3월 10일로 이동하시면 확인 가능

**Comment by Awesomeit-NSM** [comment]
@parkbeomil CP님 위에 내용을 패치해서 v5.5.9.00을 메일로 배포드렸습니다.
가능하실 때 확인을 한번 부탁드립니다.
