### ISSUE TITLE
오늘의메타학습 스크롤 관련문의

### ISSUE THREAD

**Issue by parkbeomil** [awesomeitdev/onlyonemiddle#62]
노메니저님 안녕하세요.

오늘의 메타인지 학습에서 좌우 스크롤 터치할때
이전엔  한화면씩 이동된거 같은데 지난번 부터
학습계획세운거 끝까지 스크롤이 되는거 같습니다.

확인한번 부탁드려요.

감사합니다.

**Comment by Awesomeit-NSM** [comment]
@parkbeomil CP님 좌우 버튼 탭시 페이지 단위로 이동되도록 수정해 v5.5.9.00을 메일로 배포드렸습니다.
가능하실 때 확인을 한번 부탁드립니다.
