### ISSUE TITLE
장학생 도전 2단계 성적 및 성적표 등록 API 수정 요청

### ISSUE THREAD

**Issue by KwonGeneral** [awesomeitdev/onlyonemiddle#63]
https://app.only1.co.kr/myPage/gradeShip/setStep2Action.asp
- [ API 문서에서 "https://a1.only1.co.kr/myPage/gradeShip/setStep2Action.asp" 검색하시면 됩니다. ]

현재 해당 API에서 "수정"을 할 경우, post body에 성적표1[nowScorePapper1]이 없는 경우에는 수정이 불가능합니다.
앱에서 성적표1을 다운로드 후에, 재 등록해서 전송하는 방향을 검토해 보았으나, 파일 이름이 계속 바뀌는 이슈가 생길 수 있습니다.
장학생 도전 수정 API에서 성적표1, 성적표2, 가족관계증명서가 body에 담겨져서 오지 않더라도 수정이 필요할 것 같습니다.

**Comment by Awesomeit-NSM** [comment]
추가로, 가족관계증명서가 없다고 표시되는 현상은 수정 진행했습니다.

**Comment by parkbeomil** [comment]
안녕하세요 권메니저님~

요거 파일체크가 어느타이밍에 되는것일가요? 보니까 api로 데있어서 자바스크립트는 없는걸로 보아
앱에서 체크되는거 같습니다.
혹시나 서버쪽에서 체크될가 싶어서 파일체크로직을 전부 주석처리해도 동일메세지가 뜨는데
setStep2Action.asp 리턴값 어떤건지 알 수 있을가요?

**Comment by parkbeomil** [comment]
처음등록때는 폼인코딩이 multipart/form-data 잘넘어오는데
수정할때는 일반 포스트로 오는것 같습니다. 
요거한번 확인해주셔요~~

**Comment by Awesomeit-NSM** [comment]
네 CP님 확인해보고 바로 회신드리겠습니다.

**Comment by KwonGeneral** [comment]
패킷 뜯어서 봤는데, multipart/form-data로 잘 동작하고 있습니다~!

**Comment by KwonGeneral** [comment]
```
<visang>
	<userInfo>
		<!-- 사용자 기본 정보 (모든파일에 기본으로 포함됨)-->
		<isLogin>1</isLogin>
		<!-- 로그인상태 (0:비로그인, 1:로그인) -->
		<userID>harueuki</userID>
		<mainType>smart</mainType>
		<userName>
			<![CDATA[최이연]]>
		</userName>
		<userType>S</userType>
		<userLevel>2</userLevel>
		<!-- 회원등급 (0:일반(무료), 1:유료 단강회원, 2: 무한수강) -->
		<userGrade>SA021</userGrade>
		<!-- 학년 -->
		<attentionGradeList>SA012</attentionGradeList>
		<!--나의 관심학년 들-->
		<myAttentionGradeCode>SA012</myAttentionGradeCode>
		<!--나의 대표 관심학년 -->
		<userSeedGrade>1</userSeedGrade>
		<!-- 씨앗지수등급 -->
		<hasTrial>2</hasTrial>
		<!-- 100시간체험여부 (0:경험없음, 1:체험경험있음) -->
		<defaultViewType>M</defaultViewType>
		<!-- 뷰화면 타입 (M:중등, E:초등) -->
		<periodType>
			<![CDATA[무한수강]]>
		</periodType>
		<!-- 무한수강회원이 아닌 경우 빈값) -->
		<periodTerm>652</periodTerm>
		<!-- 남은기간 숫자 (0~) -->
		<deviceID>0beb50279f973d39</deviceID>
		<!-- 기기고유코드 -->
		<deviceOS>android</deviceOS>
		<!-- iOS/android -->
		<deviceOSVersion>13</deviceOSVersion>
		<!-- os버전 -->
		<deviceModel>SM-X700</deviceModel>
		<!-- 기기모델명 -->
		<freePassHighCnt>1</freePassHighCnt>
		<!-- 고등 무한수강 권한카운트 1이상이면 수강강좌 설정/해제에서 탭노출 필요 -->
		<isFree>
			<![CDATA[0]]>
		</isFree>
		<!-- 상품 유무료 체크 [1:무료, 0:유료] -->
	</userInfo>
	<myInfo>
		<myInfoIdx>121463</myInfoIdx>
		<!-- 신청 데이터 row IDX-->
	</myInfo>
	<responseResult>
		<code>100</code>
		<value>
			<![CDATA[성적입력 및 성적표가 제출되었습니다.]]>
		</value>
	</responseResult>
</visang>
```

[ setStep2Action.asp ] 통신 시, Response 값입니다.
@parkbeomil 

추가로 [ https://app.only1.co.kr/apiList.asp ] 해당 사이트에서 [ https://app.only1.co.kr/myPage/gradeShip/setStep2Action.asp ] 이렇게 검색하면 나오는 장학생 도전 수정하기 폼에서, 테스트 했을 시에도 파일이 제대로 수정이 안되는 것 같습니다.

**Comment by Awesomeit-NSM** [comment]
현재 해당 내용 정상화를 확인했으며 이슈 클로즈하겠습니다.
