### ISSUE TITLE
[유저 환경설정] 인트로 재생 디폴트값 설정 요청

### ISSUE THREAD

**Issue by KwonGeneral** [awesomeitdev/onlyonemiddle#64]
---
###### <play_intro>]]></play_intro>
---

금일 수정 사항으로 [ 옵션 영역에 인트로 재생 디폴트값 수정 ( 켜짐 -> 꺼짐) ] 해당 요청사항을 받았는데, 해당 부분은 앱에서 설정하기가 어렵습니다.
현재 앱에서는 위 참고사항 2번 (환경설정 보기)를 통해서 값들을 가져와서 유저에게 보여주고, 유저의 액션에 따라서 1번 (환경설정 변경하기) API를 통해서 Request를 보내고 있습니다.
앱에서는 해당 유저가 인트로 재생(play_intro)을 허용을 했었는지, 안했었는지에 대한 히스토리를 추적할 수 있는 방법이 없습니다. 내부 임시 DB에 값을 저장해서 처리한다고 하더라도, 사이드 이펙트가 발생할 여지가 많습니다. 예를 들면, 해당 유저가 앱을 지웠다 설치하면 기존의 셋팅값이 날라가고 무조건 [비허용] 처리가 되던가 하는 이슈입니다.

해서, 해당 인트로 재생 디폴트값은 서버에서 체크해서, 2번 (환경설정 보기)에서 < play_intro > 필드에 넣어주실 수 있을까요?

**Comment by Awesomeit-NSM** [comment]
@leejh18Visang CP님 위에 내용 확인을 한번 부탁드립니다.

**Comment by leejh18Visang** [comment]
확인했습니다. 
영상인트로 플래그 1.켜기, 0.끄기 이렇게보시면 됩니다.

**Comment by Awesomeit-NSM** [comment]
네 CP님 앱에는 해당 값으로 처리되어있으며, 정책에 따라 값을 회신 부탁드립니다.
해당 이슈는 클로즈하겠습니다.
