### ISSUE TITLE
월말평가 웹뷰링크

### ISSUE THREAD

**Issue by leejh18Visang** [awesomeitdev/onlyonemiddle#65]
https://app.only1.co.kr/webview/getWebViewList.asp

월말평가라고 검색하시면 하단에 있습니다.

개발진행중이라 개발 후 소스는 추후에 적용예정입니다.

**Comment by Awesomeit-NSM** [comment]
@leejh18Visang 네 CP님 확인했습니다.
작업 진행하겠습니다.

**Comment by Awesomeit-NSM** [comment]
공유주신 링크로 월말평가 링크를 적용해 v5.6.4.00 앱을 메일로 배포드렸습니다.
해당 이슈는 클로즈하겠습니다.
