### ISSUE TITLE
콕강의리스트가져오기 API(https://a1.only1.co.kr/conceptSolving/getQockLectureList.asp)에서 responseResult 필드에 '본 강의는 개념문제 콕강의를 지원하지 않습니다' 를 보내줌.

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#7]
여기는 정상 통신으로 표시하고 해당 문구는 다른 필드에 적어주세요.

>박범일(비상)
알겠습니다. qockResultMessage="본 강의는 개념문제 콕강의를 지원하지 않습니다." 로 추가해놓겠습니다.

**Comment by parkbeomil** [comment]
확인결과 리스트 체크를 잘못해서 해당 문구가 출력되고 있던 것이어서 기존처럼
responseResult필드항목유지하고 메세지가 제대로 출력되게 변경하였습니다.

**Comment by KwonGeneral** [comment]
확인했습니다.
