### ISSUE TITLE
진단평가를 위한 API 요청사항

### ISSUE THREAD

**Issue by jeongyeol-son** [awesomeitdev/onlyonemiddle#8]
진단평가 (학습 앱 메인에서 나오는 플로팅 이미지를 위한 API가 필요한 듯 싶습니다.)

다만 기존에 사용하던 /main.asp api에서 floatingBannerInfo 부분과 동시에 사용하지 않는다면, 기존 부분의 데이터를 바꿔서 처리할 수도 있어 보입니다.

**Comment by parkbeomil** [comment]
네 매니저님~ 기획에 한번 확인하고 말슴드릴게요~

**Comment by parkbeomil** [comment]
기존과 동시에 올리지는 않는다고 합니다.
기존거 대신 진단평가용으로 갈이해서 올리면 될듯해요.
배너 준비되면 테스트 아이디들은 진단평가로 나오도록
갈이해 놓겠습니다.
