### ISSUE TITLE
콕강의리스트API (콕강의 지원하지 않는 경우에 대한 처리)

### ISSUE THREAD

**Issue by KwonGeneral** [awesomeitdev/onlyonemiddle#9]
https://a1.only1.co.kr/conceptSolving/getQockLectureList.asp?lp_idx=127733&l_idx=33794&ld_idx=7021080&indexType=2

해당 강좌가 콕 강의를 지원하지 않는 경우, responseResult 필드는 정상으로 표시하고
QockArray를 Empty로 주실 수 있을까요?
다른 API같은 경우에는 Empty로 처리해서 내부적으로 데이터가 Empty일때 문구를 표기하고있습니다.

현재 스마트학습앱같은 경우에는 responseResult Code에 따라서 정상이 아닌 경우를 분기처리해서 다이얼로그를 띄우던 웹뷰를 띄우던지하는 작업을 하고 있습니다.
그래서 responseResult가 정상 코드가 아닌 경우에는 에러로 판단해서 처리하기 때문에 비즈니스 로직을 짜기가 애매합니다.

**Comment by parkbeomil** [comment]
가능합니다. 바로 처리하고 회신드릴게요~

**Comment by parkbeomil** [comment]
리턴코드는 모두 100으로 정상리턴하고
참고용으로 메세지만 분기하게 처리하였습니다.

값이 없거나 지원하지 않을때는 말씀주신대로 빈값ㅈ처리했어요.
`<QockArray />`

**Comment by KwonGeneral** [comment]
확인했습니다!
